spring.application.name=agent-evaluateur

spring.ai.openai.api-key=***REMOVED***
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-120b

server.port=8081

logging.file.name=logs/agent-evaluateur.log
logging.file.max-size=10MB
logging.file.max-history=7
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.com.pfe=DEBUG
logging.level.root=INFO